# This file, makefile.bcc, is part of CWEBBIN.
# It is distributed WITHOUT ANY WARRANTY, express or implied.
# Version 3.64 [2018] --- November 2018

# Copyright (C) 1987,1990,1993,2000 Silvio Levy and Donald E. Knuth
#
# Modified for the Borland Turbo C/C++ 3.1 compiler under MS/DOS by
# Andreas Scherer (andreas.scherer@pobox.com), July 1994
# Last updated by Andreas Scherer, December 4, 2018.
# IMPORTANT NOTE: This installation was not tested.

# The following copyright notice extends to the changes in this Makefile
# only, not to any part of the original CWEB distribution.
#
# Copyright (C) 1994, 1996, 2000, 2018 Andreas Scherer

# Permission is granted to make and distribute verbatim copies of this
# document provided that the copyright notice and this permission notice
# are preserved on all copies.

# Permission is granted to copy and distribute modified versions of this
# document under the conditions for verbatim copying, provided that the
# entire resulting derived work is given a different name and distributed
# under the terms of a permission notice identical to this one.

#
# Read the README file, then edit this file to reflect local conditions
#

# directory for TeX inputs (cwebmac.tex and (X|d|f|i)cwebmac.tex and
# the 8-bit encodings go here)
MACROSDIR = ./texinputs/

# directory for CWEB inputs in @i files
CWEBINPUTS = ./cwebinputs/

# extension for manual pages ("l" distinguishes local from system stuff)
#MANEXT = l
MANEXT = 1

# directory for manual pages (cweb.1 goes here)
MANDIR = 

# destination directory for executables; must end in /
DESTDIR = ./bin/

# directory for GNU EMACS Lisp code (cweb.el goes here)
EMACSDIR = 

# directory for the language header file "cweb.h"
CATINCLUDE = ./catalogs/

# Set DESTPREF to null if you want to call the executables "tangle" and
# "weave" (probably NOT a good idea; we recommend leaving DESTPREF = c)
DESTPREF = c

# Set CCHANGES to comm-foo.ch if you need changes to common.w
CCHANGES = comm-foo.ch

# Set HCHANGES to comm-foo.hch if you need changes to common.h
HCHANGES = comm-foo.h

# Set TCHANGES to ctang-foo.ch if you need changes to ctangle.w
TCHANGES = ctang-foo.ch

# Set WCHANGES to cweav-foo.ch if you need changes to cweave.w
WCHANGES = cweav-foo.ch

# Set MCHANGES to wmerge-foo.ch if you need changes to wmerge.w
MCHANGES = wmerg-foo.ch

# Set EXTENSION to either `c' if you want to treat CWEB as a system
# of ordinary ANSI-C programs, or to `cc', `cxx', `cpp' or similar
# if you want to treat CWEB as a system of C++ programs.  Your
# compiler should be able to distinguish between the two forms
# according to the source file extension.  Even with ANSI-C programs
# it is strongly recommended to use C++ compilers, because of the
# much stricter checking of type conversions and module interfaces.
# For highest portability, all of the extra features of C++ are
# avoided in the CWEB system, thus using something like C--.
EXTENSION = cxx

# Compile with symbols.  That way you'll be able to use the debugger if
# you run into trouble.  You can always use tdstrip later, to remove the
# symbols.
DEBUG = -v

# Redundant Load Suppression (-Z) is turned off, because it seems to
# break the code.  Likewise for Copy Propagation (-Op).  (These
# optimizations don't seem to cause any problems in common.w, but
# better safe than sorry--compile everything with them turned off.)
OPT = -O2-p -Z- -mc -Ff=5000 -d -w-pro $(DEBUG)

# These lists of arguments are specific for BCC.
# Change, add or delete things here to suit your personal conditions.
# Simulate these when setting up `projects'.
CFLAGS = -I$(CATINCLUDE) $(OPT) \
	-DCWEBINPUTS="$(CWEBINPUTS)" -D_DEV_NULL="NUL" -DSEPARATORS=";\\:"
LINKFLAGS = $(CFLAGS)

# The `f' flag is turned off to save paper
# The `lX' flag includes Xcwebmac.tex
# The `s' flag displays some statistics
WFLAGS = -f +lX +s
TFLAGS = +s

# What C compiler are you using?
CC = bcc
LINK = bcc
MAKE = make

# Klaus Guntermann's Tie 2.4 processor can easily be installed on MS/DOS.
TIE = tie

# RM and CP are used below in case rm and cp are aliased
RM = del
RMDIR = deltree
CP = copy
INSTALL = copy

##########  You shouldn't have to change anything below this point #######

CWEAVE = ./cweave $(WFLAGS)
CTANGLE = ./ctangle $(TFLAGS)
WMERGE = ./wmerge

# The following files come from the original CWEB distribution and
# are left completely unmodified.

SOURCES = cweave.w common.w ctangle.w examples/wmerge.w

ORIGINAL = $(SOURCES) prod.w \
	Makefile common.c common.h ctangle.c \
	cwebman.tex cwebmac.tex comm-vms.ch ctang-vms.ch \
	cweav-vms.ch comm-man.ch ctang-man.ch cweav-man.ch \
	comm-pc.ch ctang-pc.ch cweav-pc.ch comm-amiga.ch \
        comm-bs.ch ctang-bs.ch cweav-bs.ch makefile.bs \
	comm-ql.ch ctang-ql.ch cweav-ql.ch readme.ql \
	comm-w32.ch ctang-w32.ch cweav-w32.ch \
	comm-os2.ch comm-mac.ch cweb.1 cweb.el c++lib.w README \
	examples/extex.ch examples/extex.w \
	examples/kspell.el examples/Makefile examples/README \
	examples/oemacs.el examples/oemacs.w \
	examples/treeprint.w \
	examples/wc.w examples/wc-dos.ch \
	examples/wmerg-pc.ch examples/wmer-os2.ch \
	examples/wordtest.w \
	examples/xlib_types.w examples/xview_types.w

# The following files make the body of this patched distribution
# of CWEB.

COMMPATCH = comm-ansi.ch comm-ansi.hch comm-arexx.ch comm-arexx.hch \
	comm-borlandc.ch comm-borlandc.hch comm-extensions.ch \
	comm-extensions.hch comm-i18n.ch comm-i18n.hch comm-memory.ch \
	comm-memory.hch comm-newpage.ch comm-output.ch comm-output.hch \
	comm-patch.ch comm-translation.ch comm-translation.hch \
	comm-texlive.ch comm-texlive.hch
CTANGPATCH = ctang-ansi.ch ctang-borlandc.ch ctang-extensions.ch \
	ctang-i18n.ch ctang-memory.ch ctang-newpage.ch ctang-output.ch \
	ctang-patch.ch ctang-translation.ch ctang-texlive.ch
CWEAVPATCH = cweav-ansi.ch cweav-borlandc.ch cweav-extensions.ch \
	cweav-i18n.ch cweav-newpage.ch cweav-memory.ch cweav-output.ch \
	cweav-patch.ch cweav-translation.ch cweav-texlive.ch
WMERGPATCH = wmerg-ansi.ch wmerg-borlandc.ch wmerg-extensions.ch \
	wmerg-memory.ch wmerg-output.ch wmerg-patch.ch
PATCH = common.$(EXTENSION) ctangle.$(EXTENSION) wmerge.$(EXTENSION) \
	cwebman.ch README.txt Makefile.bcc Makefile.sas Makefile.unix \
	cwebbin.spec cwebbin.dsw ctangle.dsp cweave.dsp wmerge.dsp \
	0001-Update-CWEBbin-manpage.patch ctangle.1 cweave.1

EXAMPLES = examples/cct.w examples/commonwords.w examples/extex-ansi.ch \
	examples/Makefile.sas examples/matrix.w examples/primes.ch \
	examples/primes.w examples/README.p11 examples/sample.w \
	examples/treeprint-ansi.ch examples/wc-ansi.ch \
	examples/wordtest-ansi.ch

AREXX = arexx

CATALOGS = catalogs

I18N = po

INCLUDE = cwebinputs

MACROS = texinputs

ALL = $(ORIGINAL) $(COMMPATCH) $(CTANGPATCH) $(CWEAVPATCH) $(WMERGPATCH) \
	$(PATCH) $(EXAMPLES) $(AREXX) $(CATALOGS) $(I18N) $(INCLUDE) $(MACROS)

.SUFFIXES:
.SUFFIXES: .dvi .pdf .tex .w .$(EXTENSION) .obj

.w.tex:
	$(CWEAVE) $*

.tex.dvi:
	tex $<

.tex.pdf:
	pdftex $<

.w.dvi:
	$(MAKE) $*.tex
	$(MAKE) $*.dvi

.w.pdf:
	$(MAKE) $*.tex
	$(MAKE) $*.pdf

.w.$(EXTENSION):
	$(CTANGLE) $* - $*.$(EXTENSION)

.$(EXTENSION).obj:
	$(CC) $(CFLAGS) -c $*.$(EXTENSION)

.w.obj:
	$(MAKE) $*.$(EXTENSION)
	$(MAKE) $*.obj

# When you say `make' without any arguments, `make' will jump to this item
default: boot progs

# The complete set of files contains the two programs `ctangle' and
# `cweave' plus the program `wmerge', the manuals `cwebman' and `cwebmana'
# and the source documentations.
all: progs docs

# The objects of desire
progs: ctangle.exe cweave.exe wmerge.exe

cautiously: $(CTANGLE)
	$(MAKE) SAVEcommon.$(EXTENSION)
	$(CTANGLE) common $(CCHANGES) common.$(EXTENSION)
	diff common.$(EXTENSION) SAVEcommon.$(EXTENSION)
	$(RM) SAVEcommon.$(EXTENSION)
	$(MAKE) SAVEctangle.$(EXTENSION)
	$(CTANGLE) ctangle $(TCHANGES) ctangle.$(EXTENSION)
	diff ctangle.$(EXTENSION) SAVEctangle.$(EXTENSION)
	$(RM) SAVEctangle.$(EXTENSION)

SAVEctangle.$(EXTENSION):
	$(CP) ctangle.$(EXTENSION) SAVEctangle.$(EXTENSION)

SAVEcommon.$(EXTENSION):
	$(CP) common.$(EXTENSION) SAVEcommon.$(EXTENSION)

common.$(EXTENSION): common.w $(CCHANGES)
	$(CTANGLE) common $(CCHANGES) common.$(EXTENSION)

common.obj: common.$(EXTENSION) $(CATINCLUDE)cweb.h

ctangle.exe: ctangle.obj common.obj
	$(LINK) $(LINKFLAGS) ctangle.obj common.obj

ctangle.$(EXTENSION): ctangle.w $(TCHANGES) $(HCHANGES)
	$(CTANGLE) ctangle $(TCHANGES) ctangle.$(EXTENSION)

ctangle.obj: ctangle.$(EXTENSION) $(CATINCLUDE)cweb.h $(HCHANGES)

cweave.exe: cweave.obj common.obj
	$(LINK) $(LINKFLAGS) cweave.obj common.obj

cweave.$(EXTENSION): cweave.w $(WCHANGES) $(HCHANGES)
	$(CTANGLE) cweave $(WCHANGES) cweave.$(EXTENSION)

cweave.obj: cweave.$(EXTENSION) $(CATINCLUDE)cweb.h $(HCHANGES)

wmerge.exe: wmerge.$(EXTENSION)
	$(CC) $(CFLAGS) wmerge.$(EXTENSION)

wmerge.$(EXTENSION): examples/wmerge.w $(MCHANGES)
	$(CTANGLE) examples/wmerge $(MCHANGES) wmerge.$(EXTENSION)

boot:
	$(CC) $(CFLAGS) -c ctangle.$(EXTENSION)
	$(CC) $(CFLAGS) -c common.$(EXTENSION)
	$(LINK) $(LINKFLAGS) ctangle.obj common.obj

# Take a good lecture for bedtime reading
docs: cwebman.dvi cwebmana.dvi common.dvi ctangle.dvi cweave.dvi wmerge.dvi

cwebman.dvi: cwebman.tex
cwebmana.dvi: cwebmana.tex
common.dvi: common.tex
ctangle.dvi: ctangle.tex
cweave.dvi: cweave.tex
wmerge.dvi: wmerge.tex

usermanual: cwebmana.dvi

fullmanual: usermanual $(SOURCES) \
	comm-doc.ch ctang-doc.ch cweav-doc.ch $(HCHANGES) $(MCHANGES)
	$(CWEAVE) common.w comm-doc.ch; $(MAKE) common.dvi
	$(CWEAVE) ctangle.w ctang-doc.ch; $(MAKE) ctangle.dvi
	$(CWEAVE) cweave.w cweav-doc.ch; $(MAKE) cweave.dvi
	$(CWEAVE) examples/wmerge.w $(MCHANGES); $(MAKE) wmerge.dvi

cwebmana.tex: cwebman.tex cwebman.ch
	$(TIE) -m cwebmana.tex cwebman.tex cwebman.ch

# the documentation change files are created automatically by the TIE
# processor from a set of separate change files.  note that not all
# change files listed above are actually used here, so you won't see
# any system-dependent parts not available under MS/DOS.
comm-doc.ch: common.w comm-patch.ch comm-ansi.ch comm-extensions.ch \
	comm-output.ch comm-memory.ch comm-translation.ch \
	comm-borlandc.ch comm-man.ch comm-newpage.ch
	$(TIE) -c comm-doc.ch common.w \
	comm-patch.ch comm-ansi.ch comm-extensions.ch comm-output.ch \
	comm-memory.ch comm-translation.ch comm-borlandc.ch \
	comm-man.ch comm-newpage.ch
ctang-doc.ch: ctangle.w ctang-patch.ch ctang-ansi.ch ctang-extensions.ch \
	ctang-output.ch ctang-memory.ch ctang-translation.ch \
	ctang-borlandc.ch ctang-man.ch ctang-newpage.ch
	$(TIE) -c ctang-doc.ch ctangle.w \
	ctang-patch.ch ctang-ansi.ch ctang-extensions.ch \
	ctang-output.ch ctang-memory.ch ctang-translation.ch \
	ctang-borlandc.ch ctang-man.ch ctang-newpage.ch
cweav-doc.ch: cweave.w cweav-patch.ch cweav-ansi.ch cweav-extensions.ch \
	cweav-output.ch cweav-memory.ch cweav-translation.ch \
	cweav-borlandc.ch cweav-man.ch cweav-newpage.ch
	$(TIE) -c cweav-doc.ch cweave.w \
	cweav-patch.ch cweav-ansi.ch cweav-extensions.ch cweav-output.ch \
	cweav-memory.ch cweav-translation.ch cweav-borlandc.ch \
	cweav-man.ch cweav-newpage.ch

# for making the documentation we will have to include the change files
ctangle.tex: ctangle.w $(TCHANGES) $(HCHANGES)
	$(CWEAVE) ctangle $(TCHANGES)

cweave.tex: cweave.w $(WCHANGES) $(HCHANGES)
	$(CWEAVE) cweave $(WCHANGES)

common.tex: common.w $(CCHANGES)
	$(CWEAVE) common $(CCHANGES)

wmerge.tex: examples/wmerge.w $(MCHANGES)
	$(CWEAVE) examples/wmerge $(MCHANGES)

# the master change files are created automatically by the TIE processor
# from a set of separate change files.  note that not all change files
# listed above are actually used here, so you should not try to re-port
# the resulting sources to AmigaOS.
$(CCHANGES): common.w comm-patch.ch comm-ansi.ch comm-extensions.ch \
	comm-output.ch comm-memory.ch comm-translation.ch comm-borlandc.ch
	$(TIE) -c $(CCHANGES) common.w \
	comm-patch.ch comm-ansi.ch comm-extensions.ch comm-output.ch \
	comm-memory.ch comm-translation.ch comm-borlandc.ch
$(HCHANGES): common.h comm-ansi.hch comm-extensions.hch comm-output.ch \
	comm-memory.hch comm-translation.hch comm-borlandc.hch
	$(TIE) -m $(HCHANGES) common.h \
	comm-ansi.hch comm-extensions.hch comm-output.ch comm-memory.hch \
	comm-translation.hch comm-borlandc.hch
$(TCHANGES): ctangle.w ctang-patch.ch ctang-ansi.ch ctang-extensions.ch \
	ctang-output.ch ctang-memory.ch ctang-translation.ch \
	ctang-borlandc.ch
	$(TIE) -c $(TCHANGES) ctangle.w \
	ctang-patch.ch ctang-ansi.ch ctang-extensions.ch ctang-output.ch \
	ctang-memory.ch ctang-translation.ch ctang-borlandc.ch
$(WCHANGES): cweave.w cweav-patch.ch cweav-ansi.ch cweav-extensions.ch \
	cweav-output.ch cweav-memory.ch cweav-translation.ch \
	cweav-borlandc.ch
	$(TIE) -c $(WCHANGES) cweave.w \
	cweav-patch.ch cweav-ansi.ch cweav-extensions.ch cweav-output.ch \
	cweav-memory.ch cweav-translation.ch cweav-borlandc.ch
$(MCHANGES): examples/wmerge.w wmerg-patch.ch wmerg-ansi.ch \
	wmerg-extensions.ch wmerg-output.ch wmerg-memory.ch \
	wmerg-borlandc.ch
	$(TIE) -c $(MCHANGES) examples/wmerge.w \
	wmerg-patch.ch wmerg-ansi.ch wmerg-extensions.ch wmerg-output.ch \
	wmerg-memory.ch wmerg-borlandc.ch

# be sure to leave ctangle.$(EXTENSION) and common.$(EXTENSION)
# for bootstrapping
clean:
	$(RM) *.obj
	$(RM) *.bak
	$(RM) *.log
	$(RM) *.dvi
	$(RM) *.pdf
	$(RM) *.toc
	$(RM) *.idx
	$(RM) *.scn
	$(RM) common.tex 
	$(RM) cweave.tex 
	$(RM) cweave.$(EXTENSION) 
	$(RM) wmerge.$(EXTENSION) 
	$(RM) ctangle.tex 
	$(RM) ctangle.exe
	$(RM) cweave.exe
	$(RM) wmerge.exe
	$(RM) cwebmana.tex 
	$(RM) wmerge.tex 

# Install the new program versions where they can be found
install: progs
	$(INSTALL) cweave.exe $(DESTDIR)$(DESTPREF)weave.exe
	$(INSTALL) ctangle.exe $(DESTDIR)$(DESTPREF)tangle.exe
	$(INSTALL) wmerge.exe $(DESTDIR)wmerge.exe

# Remove the original distribution completely.
remove-orig:
	- $(RM) $(ORIGINAL)

# Remove the patch completely
remove: clean
	- $(RM) $(COMMPATCH)
	- $(RM) $(CTANGPATCH)
	- $(RM) $(CWEAVPATCH)
	- $(RM) $(WMERGPATCH)
	- $(RM) $(PATCH)
	- $(RM) $(EXAMPLES)
	- $(RMDIR) $(AREXX)
	- $(RMDIR) $(CATALOGS)
	- $(RMDIR) $(I18N)
	- $(RMDIR) $(INCLUDE)
	- $(RMDIR) $(MACROS)

# End of Makefile.bcc
